version: "3.7"

services:
    web:
      container_name: nodeapp
      image: vdr007/nodeapp:v2
      build:
          context: .
          dockerfile: node.dockerfile
      networks:
        - node-mongo
      ports:
        - "3002:3000"
      volumes:
        - /home/diwakar/logs:/var/www/logs
      depends_on:
        - mongodb
    mongodb:
      container_name: mongodb
      image: mongo
      networks:
        - node-mongo
networks:
    node-mongo:
        driver: bridge

